services:
  - type: web
    name: is-chatbot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://dharaneeshrajendran2004:LOPljtBufUwSBsJK@cluster0.uzi1r.mongodb.net/isvaryam?retryWrites=true&w=majority&appName=Cluster0
